Repository PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25, pull requests merged in 2024-12, with the labels that each got.

#34 correction test1 Q6
  LCX/Test1_LCX/Q3 correction/Structogramme.PNG
  LCX/Test1_LCX/Q3 correction/ThermostaAuto.nsd
  LCX/Test1_LCX/Q3 correction/ThermostaAuto.nsd.bak
  LCX/Test1_LCX/Q3 correction/ThermostaAuto.pdf
  LCX/Test1_LCX/Q6 correction/capture solution.PNG
  LCX/Test1_LCX/Q6 correction/demoCode_frameCutting.c
  LCX/Test1_LCX/Q6 correction/main.c
  LCX/Test1_LCX/Q6 correction/testFunctions.h
Labels: bug, documentation, invalid, specification, improvement, Todo

#37 correction Q3 Q6
  ARD/Q3/AlexandreRabald_Capteur_de_température.pdf
  ARD/Q3/AlexandreRabald_Capteur_de_températurecorrigé.nsd
  ARD/Q3/AlexandreRabald_Capteur_de_températurecorrigé.nsd.bak
  ARD/Q6/.vs/Test1_JJE/FileContentIndex/027b545f-aee6-4f9c-99e3-190d4e52a8c3.vsidx
  ARD/Q6/.vs/Test1_JJE/FileContentIndex/5f750845-de2e-4568-9cca-28037fe758ed.vsidx
  ARD/Q6/.vs/Test1_JJE/FileContentIndex/8243d0d6-7b73-403c-a726-775cae963f63.vsidx
  ARD/Q6/.vs/Test1_JJE/FileContentIndex/93fb77c9-a58a-4c9f-b8e8-2ce172d8a54a.vsidx
  ARD/Q6/.vs/Test1_JJE/FileContentIndex/read.lock
  ARD/Q6/.vs/Test1_JJE/v17/.suo
  ARD/Q6/.vs/Test1_JJE/v17/Browse.VC.db
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/15bbb4a73ba3abc8/DEMOCODE_FRAMECUTTING.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/2f3ca2d65dd53be5/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/63da890182d8bdff/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/706cb0bc358b760b/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/a35cf024a74e7c9d/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/afe434eb7bdc0019/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/c7d1e393ad283d0f/SOURCE.ipch
  ARD/Q6/.vs/Test1_JJE/v17/ipch/AutoPCH/f904aabc607b14db/MAIN.ipch
  ARD/Q6/Test1_JJE.sln
  ARD/Q6/Test1_JJE/AlexandreRabaldProgramation - Raccourci.lnk
  ARD/Q6/Test1_JJE/Test1_JJE.vcxproj
  ARD/Q6/Test1_JJE/Test1_JJE.vcxproj.filters
  ARD/Q6/Test1_JJE/Test1_JJE.vcxproj.user
  ARD/Q6/Test1_JJE/demoCode_frameCutting.c
  ARD/Q6/Test1_JJE/main.c
  ARD/Q6/Test1_JJE/testFunctions.h
  ARD/Q6/Test1_JJE/x64/Debug/Source.obj
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.exe.recipe
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.ilk
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.log
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/CL.command.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/CL.read.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/CL.write.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/Test1_JJE.lastbuildstate
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/link.command.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/link.read.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/Test1_JJE.tlog/link.write.1.tlog
  ARD/Q6/Test1_JJE/x64/Debug/_IsIncrementalBuild
  ARD/Q6/Test1_JJE/x64/Debug/demoCode_frameCutting.obj
  ARD/Q6/Test1_JJE/x64/Debug/democode_framecutting.obj.enc
  ARD/Q6/Test1_JJE/x64/Debug/main.obj
  ARD/Q6/Test1_JJE/x64/Debug/vc143.idb
  ARD/Q6/Test1_JJE/x64/Debug/vc143.pdb
  ARD/Q6/Test1_JJE/x64/Debug/vcpkg.applocal.log
  ARD/Q6/photo console.png
  ARD/Q6/x64/Debug/Test1_JJE.exe
  ARD/Q6/x64/Debug/Test1_JJE.pdb
  ARD/Test1_ARB/Q3/AlexandreRabald_Capteur_de_température.nsd
Labels: bug, documentation, invalid, question, wontfix, specification, improvement, Todo, validation porgress

#31 coorection version RBN
  RBN/.vs/RBN/FileContentIndex/caba8317-e02d-4c36-93f2-6b7538700794.vsidx
  RBN/.vs/RBN/FileContentIndex/read.lock
  RBN/.vs/RBN/v17/.suo
  RBN/.vs/VSWorkspaceState.json
  RBN/.vs/slnx.sqlite
  RBN/Capteur_de_temperature_1-exterieur.nsd
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/FileContentIndex/4ea255de-2dba-417c-bebd-9ba133067c80.vsidx
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/FileContentIndex/6b2ff095-e3d2-4293-84b9-42475296e327.vsidx
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/FileContentIndex/d3235bce-4680-4a15-b542-5dc16bc8c60d.vsidx
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/FileContentIndex/e542ed65-04b9-412a-9a9d-a640009779d2.vsidx
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/FileContentIndex/read.lock
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/v17/.suo
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/v17/Browse.VC.db
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/v17/ipch/AutoPCH/4467c23bdc5af68/DEMOCODE_FRAMECUTTING.ipch
  RBN/CoorectionQ6/corrige te1 prog/.vs/corrige te1 prog/v17/ipch/AutoPCH/ead6970f47fb25bb/MAIN.ipch
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog.sln
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/corrige te1 prog.vcxproj
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/corrige te1 prog.vcxproj.filters
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/corrige te1 prog.vcxproj.user
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/demoCode_frameCutting.c
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/main.c
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/testFunctions.h
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/_IsIncrementalBuild
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.exe.recipe
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.ilk
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.log
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/CL.command.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/CL.read.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/CL.write.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/corrige te1 prog.lastbuildstate
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/link.command.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/link.read.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/corrige te1 prog.tlog/link.write.1.tlog
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/demoCode_frameCutting.obj
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/democode_framecutting.obj.enc
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/main.obj
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/vc143.idb
  RBN/CoorectionQ6/corrige te1 prog/corrige te1 prog/x64/Debug/vc143.pdb
  RBN/CoorectionQ6/corrige te1 prog/x64/Debug/corrige te1 prog.exe
  RBN/CoorectionQ6/corrige te1 prog/x64/Debug/corrige te1 prog.pdb
  RBN/CorrectionQ3/Capteur_de_temperature_1-exterieur.nsd
  RBN/CorrectionQ3/Capteur_de_temperature_1-exterieur.nsd.bak
  RBN/CorrectionQ3/Correction Q3 V2.pdf
  RBN/CorrectionQ3/correction structogramme.pdf
  RBN/CorrectionQ3/corriger renato.nsd
  RBN/CorrectionQ3/corrigé question 3.pdf
Labels: bug, documentation, invalid, specification, improvement, Todo

#33 Correction du test de prog
  DSY/Q3/Correctif_Test1_Prog_DSY.pdf
  DSY/Q3/correction test prog 1.nsd
  DSY/Q3/correction test prog 1.nsd.bak
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/FileContentIndex/5e466b9d-c3ae-4d21-b817-9a86351d7199.vsidx
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/FileContentIndex/c9ec172b-cbb4-459d-825d-5351ecebc29a.vsidx
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/FileContentIndex/read.lock
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/v17/.suo
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/v17/Browse.VC.db
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/v17/ipch/AutoPCH/1ce1925ea32cd6c3/MAIN.ipch
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/v17/ipch/AutoPCH/b083c9cef60d13c0/DEMOCODE_FRAMECUTTING.ipch
  DSY/Q6/Correction_Test1_DSY/.vs/Correction_Test1_DSY/v17/ipch/AutoPCH/c4ded4a268ed592/DEMOCODE_FRAMECUTTING.ipch
  DSY/Q6/Correction_Test1_DSY/Capture d’écran 2024-11-19 130246.png
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY.sln
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/Correction_Test1_DSY.vcxproj
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/Correction_Test1_DSY.vcxproj.filters
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/Correction_Test1_DSY.vcxproj.user
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/demoCode_frameCutting.c
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/main.c
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/testFunctions.h
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/CL.command.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/CL.read.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/CL.write.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/Correction_Test1_DSY.lastbuildstate
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/link.command.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/link.read.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correcti.b2a872f5.tlog/link.write.1.tlog
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correction_Test1_DSY.exe.recipe
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correction_Test1_DSY.ilk
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/Correction_Test1_DSY.log
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/demoCode_frameCutting.obj
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/main.obj
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/vc143.idb
  DSY/Q6/Correction_Test1_DSY/Correction_Test1_DSY/x64/Debug/vc143.pdb
  DSY/Q6/Correction_Test1_DSY/x64/Debug/Correction_Test1_DSY.exe
  DSY/Q6/Correction_Test1_DSY/x64/Debug/Correction_Test1_DSY.pdb
Labels: bug, documentation, enhancement, invalid, question, wontfix, specification, improvement, Todo, validation porgress

#38 correction de Q6
  ANE/Q3/correction Q3 en PDF.pdf
  ANE/Q3/correction Q3.nsd
  ANE/Q3/correction Q3.nsd.bak
  ANE/Q6/Correction Q6/.vs/Correction Q6/FileContentIndex/1e56bca4-f31b-432c-9f07-6380512baba7.vsidx
  ANE/Q6/Correction Q6/.vs/Correction Q6/FileContentIndex/read.lock
  ANE/Q6/Correction Q6/.vs/Correction Q6/v17/.suo
  ANE/Q6/Correction Q6/.vs/Correction Q6/v17/Browse.VC.db
  ANE/Q6/Correction Q6/.vs/Correction Q6/v17/ipch/AutoPCH/1923eb8070b0a786/DEMOCODE_FRAMECUTTING.ipch
  ANE/Q6/Correction Q6/.vs/Correction Q6/v17/ipch/AutoPCH/ec15c6243fdc1ebd/MAIN.ipch
  ANE/Q6/Correction Q6/Correction Q6.sln
  ANE/Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj
  ANE/Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj.filters
  ANE/Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj.user
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.exe.recipe
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.ilk
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.log
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.command.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.read.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.write.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/Correction Q6.lastbuildstate
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.command.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.read.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.write.1.tlog
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/_IsIncrementalBuild
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/demoCode_frameCutting.obj
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/main.obj
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/vc143.idb
  ANE/Q6/Correction Q6/Correction Q6/x64/Debug/vc143.pdb
  ANE/Q6/Correction Q6/x64/Debug/Correction Q6.exe
  ANE/Q6/Correction Q6/x64/Debug/Correction Q6.pdb
  ANE/Q6/demoCode_frameCutting.c
  ANE/Q6/main.c
  ANE/Q6/resultat du programme.png
  ANE/Q6/testFunctions.h
Labels: bug, documentation, enhancement, invalid, question, wontfix, specification, improvement, validation porgress

#39 correction Q6
  FGT/Q3 correction/GestionDomotique.nsd
  FGT/Q3 correction/GestionDomotique.nsd.bak
  FGT/Q3 correction/GestionDomotique2.nsd
  FGT/Q3 correction/GestionDomotique2.pdf
  FGT/Q3 correction/gestion de température.pdf
  FGT/Q3 correction/structo gest temp.nsd
  FGT/Q6 correction/Capture.PNG
  FGT/Q6 correction/Q6 correction/.vs/Q6 correction/v17/.suo
  FGT/Q6 correction/Q6 correction/.vs/Q6 correction/v17/Browse.VC.db
  FGT/Q6 correction/Q6 correction/.vs/Q6 correction/v17/ipch/AutoPCH/3306be99159193f0/DEMOCODE_FRAMECUTTING.ipch
  FGT/Q6 correction/Q6 correction/.vs/Q6 correction/v17/ipch/AutoPCH/80142b296e1e95b3/MAIN.ipch
  FGT/Q6 correction/Q6 correction/Q6 correction.sln
  FGT/Q6 correction/Q6 correction/Q6 correction/Q6 correction.vcxproj
  FGT/Q6 correction/Q6 correction/Q6 correction/Q6 correction.vcxproj.filters
  FGT/Q6 correction/Q6 correction/Q6 correction/Q6 correction.vcxproj.user
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.exe.recipe
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.ilk
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.log
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/CL.command.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/CL.read.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/CL.write.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/Q6 correction.lastbuildstate
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/link.command.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/link.read.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/Q6 correction.tlog/link.write.1.tlog
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/_IsIncrementalBuild
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/demoCode_frameCutting.obj
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/main.obj
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/vc143.idb
  FGT/Q6 correction/Q6 correction/Q6 correction/x64/Debug/vc143.pdb
  FGT/Q6 correction/Q6 correction/x64/Debug/Q6 correction.exe
  FGT/Q6 correction/Q6 correction/x64/Debug/Q6 correction.pdb
  FGT/Q6 correction/demoCode_frameCutting.c
  FGT/Q6 correction/erreur.PNG
  FGT/Q6 correction/list.PNG
  FGT/Q6 correction/main.c
  FGT/Q6 correction/testFunctions.h
Labels: bug, documentation, enhancement, invalid, question, wontfix, specification, improvement, validation porgress
