Repository PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25, pull requests merged in 2024-11, with the labels that each got.

#35 Correction de Q3 du test de prog
  KGR/Test1_KGR/Correction Q3/Boucle Do while.png
  KGR/Test1_KGR/Correction Q3/Boucle FOR.png
  KGR/Test1_KGR/Correction Q3/Boucle TANTQUE FAIRE.png
  KGR/Test1_KGR/Correction Q3/Boucle While(1).png
  KGR/Test1_KGR/Correction Q3/Correction_Question_3.nsd
  KGR/Test1_KGR/Correction Q3/Correction_Question_3.nsd.bak
  KGR/Test1_KGR/Correction Q3/Correction_Question_3.pdf
  KGR/Test1_KGR/Correction Q3/Correction_Question_3.png
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/FileContentIndex/75dd2653-92b4-49a6-ac54-31079f3ae396.vsidx
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/FileContentIndex/read.lock
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/v17/.suo
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/v17/Browse.VC.db
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/v17/ipch/AutoPCH/a9e3c1b9f7ade698/DEMOCODE_FRAMECUTTING.ipch
  KGR/Test1_KGR/Correction Q6/Correction Q6/.vs/Correction Q6/v17/ipch/AutoPCH/e862cb75eb01852b/MAIN.ipch
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6.sln
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj.filters
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/Correction Q6.vcxproj.user
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.exe.recipe
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.ilk
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.log
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.command.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.read.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/CL.write.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/Correction Q6.lastbuildstate
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.command.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.read.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/Correction Q6.tlog/link.write.1.tlog
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/demoCode_frameCutting.obj
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/main.obj
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/vc143.idb
  KGR/Test1_KGR/Correction Q6/Correction Q6/Correction Q6/x64/Debug/vc143.pdb
  KGR/Test1_KGR/Correction Q6/Correction Q6/x64/Debug/Correction Q6.exe
  KGR/Test1_KGR/Correction Q6/Correction Q6/x64/Debug/Correction Q6.pdb
  KGR/Test1_KGR/Correction Q6/Résultat du code.png
  KGR/Test1_KGR/Correction Q6/demoCode_frameCutting.c
  KGR/Test1_KGR/Correction Q6/main.c
  KGR/Test1_KGR/Correction Q6/testFunctions.h
Labels: validation porgress

#30 Q6 à corriger
  BZI/Q3/Question_3 strutograme version 2.nsd
  BZI/Q3/Question_3 strutograme.nsd
  BZI/Q3/Question_3 strutograme.nsd.bak
  BZI/Q3/Question_3.pdf
  BZI/Q3/Question_3_CorrectionAvecMonMeilleurAmis.pdf
  BZI/Q6/Capture. du cmdPNG.PNG
  BZI/Q6/Q6/.vs/Q6/FileContentIndex/7a2fcc12-bb69-4296-a744-98e47a5671bc.vsidx
  BZI/Q6/Q6/.vs/Q6/FileContentIndex/read.lock
  BZI/Q6/Q6/.vs/Q6/v17/.suo
  BZI/Q6/Q6/.vs/Q6/v17/Browse.VC.db
  BZI/Q6/Q6/.vs/Q6/v17/Browse.VC.db-shm
  BZI/Q6/Q6/.vs/Q6/v17/Browse.VC.db-wal
  BZI/Q6/Q6/.vs/Q6/v17/ipch/AutoPCH/2dca508beed74c71/MAIN.ipch
  BZI/Q6/Q6/.vs/Q6/v17/ipch/AutoPCH/603cb59b55735722/DEMOCODE_FRAMECUTTING.ipch
  BZI/Q6/Q6/Q6.sln
  BZI/Q6/Q6/Q6/Q6.vcxproj
  BZI/Q6/Q6/Q6/Q6.vcxproj.filters
  BZI/Q6/Q6/Q6/Q6.vcxproj.user
  BZI/Q6/Q6/Q6/demoCode_frameCutting.c
  BZI/Q6/Q6/Q6/main.c
  BZI/Q6/Q6/Q6/testFunctions.h
  BZI/Q6/Q6/Q6/x64/Debug/Q6.exe.recipe
  BZI/Q6/Q6/Q6/x64/Debug/Q6.ilk
  BZI/Q6/Q6/Q6/x64/Debug/Q6.log
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/CL.command.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/CL.read.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/CL.write.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/Q6.lastbuildstate
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/link.command.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/link.read.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/Q6.tlog/link.write.1.tlog
  BZI/Q6/Q6/Q6/x64/Debug/demoCode_frameCutting.obj
  BZI/Q6/Q6/Q6/x64/Debug/main.obj
  BZI/Q6/Q6/Q6/x64/Debug/vc143.idb
  BZI/Q6/Q6/Q6/x64/Debug/vc143.pdb
  BZI/Q6/Q6/x64/Debug/Q6.exe
  BZI/Q6/Q6/x64/Debug/Q6.pdb
Labels: bug, documentation, invalid, wontfix, specification, improvement, Todo, validation porgress

#36 première itération correction Test_1
  LFO/Test1_LFO/Q3/PROG_TEST1_Question_3_Corriger.pdf
  LFO/Test1_LFO/Q3/PROG_TEST1_Question_3_Corriger.png
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/.vs/PROG_Test1_Q6/v17/.suo
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/.vs/PROG_Test1_Q6/v17/Browse.VC.db
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/.vs/PROG_Test1_Q6/v17/ipch/AutoPCH/1cc74e0da8afbba4/MAIN.ipch
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/.vs/PROG_Test1_Q6/v17/ipch/AutoPCH/507f131c39fd129/DEMOCODE_FRAMECUTTING.ipch
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/PROG_Test1_Q6.sln
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/PROG_Test1_Q6.vcxproj
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/PROG_Test1_Q6.vcxproj.filters
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/PROG_Test1_Q6.vcxproj.user
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.exe
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.exe.recipe
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.ilk
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.log
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.pdb
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/CL.command.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/CL.read.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/CL.write.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/PROG_Test1_Q6.lastbuildstate
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/link.command.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/link.read.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.tlog/link.write.1.tlog
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/PROG_Test1_Q6.vcxproj.FileListAbsolute.txt
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/demoCode_frameCutting.obj
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/main.obj
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/vc143.idb
  LFO/Test1_LFO/Q6/PROG_Test1_Q6/x64/Debug/vc143.pdb
  LFO/Test1_LFO/Q6/demoCode_frameCutting.c
  LFO/Test1_LFO/Q6/main.c
  LFO/Test1_LFO/Q6/resultat_Q6.png
  LFO/Test1_LFO/Q6/testFunctions.h
Labels: bug, documentation, enhancement, invalid, question, wontfix, specification, improvement, Todo, validation porgress
